export const INITIATIVE_CATEGORIES = ["EDUCATIONAL", "COMMUNITY", "NATIONAL", "INNOVATION", "HEALTH_SAFETY", "OTHER"] as const;

export const INITIATIVE_STATUSES = ["DRAFT", "ACTIVE", "COMPLETED"] as const;
